apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: train-trans-template
  labels:
    scenarios.ai.sap.com/id: "train-trans-scenario"
    executables.ai.sap.com/id: "train-trans-executable"
    ai.sap.com/version: "1.0.0"
  annotations:
    executables.ai.sap.com/name: "train-trans-template"
spec:
  entrypoint: train-trans-template
  templates:
    - name: train-trans-template
      steps:
        - - name: training-step
            template: training-step
    - name: training-step
      metadata:
        labels:
          ai.sap.com/resourcePlan: train.l
      container:
        image: docker.io/rahulcruze786/ml_training_model:0.0.2
        command: ["/bin/sh", "-c"]
        args:
          - gunicorn --bind 0.0.0.0:8080 app:app
        volumeMounts:
          - name: output
            mountPath: /app/models
      outputs:
        artifacts:
          - name: trained-models
            path: /app/models
            archive:
              none: {}
