apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ml-training-model
  labels:
    scenarios.ai.sap.com/id: "ml-classification-scenario"
    executables.ai.sap.com/id: "ml-training"
    ai.sap.com/version: "1.0.0"
  annotations:
    executables.ai.sap.com/name: "ml-training-model"
spec:
  entrypoint: ml-training-model
  templates:
    - name: ml-training-model
      steps:
        - - name: training-step
            template: training-step
    - name: training-step
      metadata:
        labels:
          ai.sap.com/resourcePlan: train.l
      container:
        image: docker.io/rahulcruze786/ml_training_model:0.0.1
        command: ["/bin/sh", "-c"]
        args:
          - gunicorn --bind 0.0.0.0:5000 app:app
        volumeMounts:
          - name: output
            mountPath: /app/models
      outputs:
        artifacts:
          - name: trained-models
            path: /app/models
            archive:
              none: {}
